name: Build 

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select branch to build(default: master)'
        required: false
        default: 'master'
jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkitarm'

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: build
        run: make build-all
