name: Build 

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select branch to build(default: master)'
        required: false
        default: 'master'
jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkitarm:20180522'

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build the homebrew 
        run: make all

      - uses: actions/upload-artifact@v4
        with:
          name: ctruLua
          path: /home/runner/work/ctruLua/ctruLua
